---
jobs:
- name: job-get-version
  public: true
  serial: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: bump-timestamp-file
    file: resource-tutorial/bump-timestamp-file.yml
  - task: show-some-files
    file: resource-tutorial/tag-files.yml
    params: {save: true}
  - put: hello-world-docker-image
    params: {build: resource-tutorial/docker, tag: some-files/.txt}
- name: Image-Pull-and-Run
  public: true
  serial: true
  plan:
  - get: hello-world-docker-image
  - get: resource-tutorial
    passed: [job-get-version]
    trigger: true
  - task: bump-timestamp-file
    file: resource-tutorial/bump-timestamp-file.yml
    params: {save: true}
  - task: show-some-files
    inputs:
    - name: resource-tutorial
    - name: some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: dhaneshande/nodeappbuild, tag: 'some-files/.txt'}
        inputs:
        - name: resource-tutorial
      run:
        path: /bin/bash
        args:
        - -exc
        - |
          pwd
          cd /usr/src/app
          ls -la
          npm start
          exit		  
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/dhaneshande/VersioningPart1.git
- name: hello-world-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}
